name: 'Setup Steam Depot Downloader'
description: 'Setup Steam Depot Downloader'
author: 'dumbasPL'

inputs:
  version:
    description: 'Steam Depot Downloader version'
    required: false
    default: 'latest'
  test:
    description: 'Whether to run DepotDownloader (with no arguments) in order to check if it works'
    required: false
    default: 'true'

runs:
  using: 'node24'
  main: 'dist/index.js'

branding:
  icon: 'download'
  color: 'blue'